### ISSUE TITLE
the problem about official version

### ISSUE THREAD

**Issue by mumuyanyan** [manicman1999/StyleGAN2-Tensorflow-2.0#1]
the implements of official stylegan2 come to the problem
 #error This file requires compiler and library support for the ISO C++ 2011 standard.
This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support \

do you meet the same problem?thanks

**Comment by manicman1999** [comment]
This implementation is unofficial, and thus is incompatible with the original stylegan2 implementation. This also means saving and loading models between these implementations is also not possible (at least not yet).

**Comment by cellininicholas** [comment]
Has this changed at all?
Can models trained using the NVLabs implementation [github.com/NVlabs/stylegan2](https://github.com/NVlabs/stylegan2), still not be loaded into this implementation?
