### ISSUE TITLE
About model conversion

### ISSUE THREAD

**Issue by oovm** [manicman1999/StyleGAN2-Tensorflow-2.0#2]
Is there way to dump the official model weights and load into this version?

**Comment by manicman1999** [comment]
Unfortunately not, the official model weights are using some custom libraries NVidia created, while my implementation is only using Tensorflow 2.0, thus the model weight files would have to be reconfigured - something I'm not well versed enough to do yet.

**Comment by oovm** [comment]
Oh, I see, thanks
